server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456



mybatis-plus:
  type-aliases-package: com.emiyez.springboot01.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      logic-delete-field: isDel
      logic-delete-value: 1
      logic-not-delete-value: 0

name: abc

